version: '3.8'

services:
  deepseek-proxy:
    image: deepseek/api-gateway:2.3
    environment:
      API_KEY: ${DEEPSEEK_API_KEY}
    ports:
      - "8080:8080"

  ollama:
    image: ollama/ollama:0.1.30
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data: