name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      
      - name: Install dependencies
        run: make deps
      
      - name: Run tests
        run: make test
      
      - name: Run linter
        run: make lint
      
      - name: Build CLI
        run: make build

      - name: Upload CLI binary
        uses: actions/upload-artifact@v3
        with:
          name: thresh
          path: bin/thresh